#!/usr/bin/env python
import rospy
from visualization_msgs.msg import Marker
from nav_msgs.msg import Odometry


class VisualizerNode():
    def __init__(self):
        rospy.init_node("rviz_visualizer")
        self.bluerov_marker_pub = rospy.Publisher("vehicle_marker",
                                                  Marker,
                                                  queue_size=30)

        self.namespace = rospy.get_namespace().strip("/")
        self.ground_truth_sub = rospy.Subscriber("ground_truth/state", Odometry,
                                                 self.on_ground_truth)

    def run(self):
        rospy.spin()

    def publish_marker(self, pose, header):
        msg = Marker()
        msg.header = header
        msg.ns = self.namespace
        msg.id = 27
        msg.type = Marker.MESH_RESOURCE
        msg.pose = pose
        msg.mesh_resource = "package://hippocampus_sim/models/uuv_hippocampus/meshes/uuv_hippocampus.stl"
        msg.color.a = 1.0
        msg.color.r = 1.0
        msg.color.g = 1.0
        msg.color.b = 1.0
        msg.scale.x = 1
        msg.scale.y = 1
        msg.scale.z = 1
        self.bluerov_marker_pub.publish(msg)

    def on_ground_truth(self, msg):
        self.publish_marker(msg.pose.pose, msg.header)


def main():
    node = VisualizerNode()
    node.run()


if __name__ == "__main__":
    main()
